services:
    ubuntu:
        public: true
        container_name: yg
        image: imlala/ubuntu-xfce-vnc-novnc:latest
        ports:
            - 6080:6080
        environment: 
            - VNC_PASSWD=+DBc)tsA2#7f.{zL
            - GEOMETRY=1280x768
            - TZ=Asia/India
            - DEPTH=24
        volumes: 
            - /root/Desktop
            - /home
        resources:
          cpu: 2000m
          memory: 6072Mi
          storage:
            size: 1Gi
            class: standard
